//go:build go1.22

// Package webui provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package webui

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for EventType.
const (
	Hello    EventType = "hello"
	Pool     EventType = "pool"
	Workflow EventType = "workflow"
)

// Valid indicates whether the value is a known member of the EventType enum.
func (e EventType) Valid() bool {
	switch e {
	case Hello:
		return true
	case Pool:
		return true
	case Workflow:
		return true
	default:
		return false
	}
}

// Defines values for VMState.
const (
	VMStateAcquired  VMState = "acquired"
	VMStateAvailable VMState = "available"
	VMStateCreating  VMState = "creating"
	VMStateDeleted   VMState = "deleted"
	VMStateFailed    VMState = "failed"
	VMStateStaging   VMState = "staging"
	VMStateStopped   VMState = "stopped"
	VMStateUnknown   VMState = "unknown"
)

// Valid indicates whether the value is a known member of the VMState enum.
func (e VMState) Valid() bool {
	switch e {
	case VMStateAcquired:
		return true
	case VMStateAvailable:
		return true
	case VMStateCreating:
		return true
	case VMStateDeleted:
		return true
	case VMStateFailed:
		return true
	case VMStateStaging:
		return true
	case VMStateStopped:
		return true
	case VMStateUnknown:
		return true
	default:
		return false
	}
}

// Defines values for WorkflowState.
const (
	WorkflowStateAcquiring   WorkflowState = "acquiring"
	WorkflowStateCanceled    WorkflowState = "canceled"
	WorkflowStateCompleted   WorkflowState = "completed"
	WorkflowStateFailed      WorkflowState = "failed"
	WorkflowStateQueued      WorkflowState = "queued"
	WorkflowStateRunning     WorkflowState = "running"
	WorkflowStateVmCompleted WorkflowState = "vm_completed"
)

// Valid indicates whether the value is a known member of the WorkflowState enum.
func (e WorkflowState) Valid() bool {
	switch e {
	case WorkflowStateAcquiring:
		return true
	case WorkflowStateCanceled:
		return true
	case WorkflowStateCompleted:
		return true
	case WorkflowStateFailed:
		return true
	case WorkflowStateQueued:
		return true
	case WorkflowStateRunning:
		return true
	case WorkflowStateVmCompleted:
		return true
	default:
		return false
	}
}

// BuildInfo defines model for BuildInfo.
type BuildInfo struct {
	// Arch Example: arm64
	Arch string `json:"arch"`

	// BuildTime Example: 2026-09-03T18:00:00Z
	BuildTime *string `json:"build_time,omitempty"`

	// GoVersion Example: go1.24.0
	GoVersion string `json:"go_version"`

	// Modified Example: false
	Modified *bool `json:"modified,omitempty"`

	// Os Example: darwin
	Os string `json:"os"`

	// Path Example: github.com/cloudengio/citools/runners/macos/orchestrator
	Path *string `json:"path,omitempty"`

	// Revision Example: e005e3a0b1c2...
	Revision *string `json:"revision,omitempty"`

	// RevisionShort Example: e005e3a0
	RevisionShort *string `json:"revision_short,omitempty"`

	// RevisionTime Example: 2026-09-03T17:15:00Z
	RevisionTime *string `json:"revision_time,omitempty"`

	// Version Example: v0.1.0
	Version *string `json:"version,omitempty"`
}

// ConfigSummary defines model for ConfigSummary.
type ConfigSummary struct {
	// ConfigFile Path to the YAML config file this orchestrator was started with.
	ConfigFile   string              `json:"config_file"`
	Global       GlobalConfigSummary `json:"global"`
	Pools        []PoolConfigSummary `json:"pools"`
	Repositories []RepositorySummary `json:"repositories"`
	Webhook      WebhookSummary      `json:"webhook"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Event defines model for Event.
type Event struct {
	Pool      *PoolStatus     `json:"pool,omitempty"`
	Timestamp time.Time       `json:"timestamp"`
	Type      EventType       `json:"type"`
	Workflow  *WorkflowStatus `json:"workflow,omitempty"`
}

// EventType defines model for Event.Type.
type EventType string

// GlobalConfigSummary defines model for GlobalConfigSummary.
type GlobalConfigSummary struct {
	CompletionQueueSize *int `json:"completion_queue_size,omitempty"`

	// FailedVmRetentionPeriod Go duration string, e.g. "30m".
	FailedVmRetentionPeriod     *string `json:"failed_vm_retention_period,omitempty"`
	SuccessfulVmRetentionPeriod *string `json:"successful_vm_retention_period,omitempty"`
	TmpDir                      *string `json:"tmp_dir,omitempty"`
}

// LogArtifact defines model for LogArtifact.
type LogArtifact struct {
	ContentType *string `json:"content_type,omitempty"`
	Filename    string  `json:"filename"`

	// Href Relative URL to download this artifact.
	Href string `json:"href"`

	// Id Stable artifact id, e.g. "job" or "diag".
	Id        string `json:"id"`
	SizeBytes *int64 `json:"size_bytes,omitempty"`
}

// PoolConfigSummary defines model for PoolConfigSummary.
type PoolConfigSummary struct {
	Image     *string `json:"image,omitempty"`
	Name      *string `json:"name,omitempty"`
	RunnerDir *string `json:"runner_dir,omitempty"`
	Size      *int    `json:"size,omitempty"`
}

// PoolStatus defines model for PoolStatus.
type PoolStatus struct {
	Image *string `json:"image,omitempty"`

	// Kind The VM backend kind for this pool, e.g. "tart".
	Kind *string `json:"kind,omitempty"`
	Name string  `json:"name"`

	// Size Configured pool size (target number of warm VMs).
	Size int        `json:"size"`
	Vms  []VMStatus `json:"vms"`
}

// RepositorySummary defines model for RepositorySummary.
type RepositorySummary struct {
	Owner   *string          `json:"owner,omitempty"`
	Repo    *string          `json:"repo,omitempty"`
	Runners *[]RunnerSummary `json:"runners,omitempty"`
}

// RunnerSummary defines model for RunnerSummary.
type RunnerSummary struct {
	Labels     *[]string `json:"labels,omitempty"`
	NamePrefix *string   `json:"name_prefix,omitempty"`
	VmPool     *string   `json:"vm_pool,omitempty"`
}

// ServiceStatus defines model for ServiceStatus.
type ServiceStatus struct {
	// Installed Whether the launchd login service is installed.
	Installed bool `json:"installed"`

	// Label The service label / bundle ID.
	Label *string `json:"label,omitempty"`

	// Running Whether the orchestrator is currently running as a service.
	Running bool `json:"running"`
}

// VMState State of a VM as reported by the pool.
type VMState string

// VMStatus defines model for VMStatus.
type VMStatus struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        string     `json:"id"`

	// LastEvent The most recent pool event kind observed for this VM.
	LastEvent *string `json:"last_event,omitempty"`
	Name      *string `json:"name,omitempty"`
	Pool      *string `json:"pool,omitempty"`

	// State State of a VM as reported by the pool.
	State     VMState    `json:"state"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// WebhookSummary defines model for WebhookSummary.
type WebhookSummary struct {
	RelayUrl *string `json:"relay_url,omitempty"`
}

// WorkflowState Lifecycle state of a workflow job within the orchestrator. `vm_completed` means the job finished on the local VM but GitHub has not yet delivered the completion webhook; `completed` means GitHub acknowledged completion.
type WorkflowState string

// WorkflowStatus defines model for WorkflowStatus.
type WorkflowStatus struct {
	// CompletedAt When GitHub acknowledged completion.
	CompletedAt *time.Time `json:"completed_at,omitempty"`

	// Error Error detail if the job failed or was canceled.
	Error   *string `json:"error,omitempty"`
	JobId   *int64  `json:"job_id,omitempty"`
	JobName *string `json:"job_name,omitempty"`

	// JobUrl URL to the workflow run job on GitHub (e.g. https://github.com/<owner>/<repo>/actions/runs/<run_id>/job/<job_id>).
	JobUrl *string        `json:"job_url,omitempty"`
	Labels *[]string      `json:"labels,omitempty"`
	Logs   *[]LogArtifact `json:"logs,omitempty"`

	// Name The runner instance name assigned by the orchestrator.
	Name         string     `json:"name"`
	Pool         *string    `json:"pool,omitempty"`
	QueuedAt     *time.Time `json:"queued_at,omitempty"`
	RepoFullName *string    `json:"repo_full_name,omitempty"`
	RepoUrl      *string    `json:"repo_url,omitempty"`

	// Result Terminal result if completed, e.g. "Succeeded".
	Result    *string    `json:"result,omitempty"`
	RunId     *int64     `json:"run_id,omitempty"`
	StartedAt *time.Time `json:"started_at,omitempty"`

	// State Lifecycle state of a workflow job within the orchestrator. `vm_completed` means the job finished on the local VM but GitHub has not yet delivered the completion webhook; `completed` means GitHub acknowledged completion.
	State WorkflowState `json:"state"`

	// VmCompletedAt When the job finished running on the local VM.
	VmCompletedAt *time.Time `json:"vm_completed_at,omitempty"`
	VmId          *string    `json:"vm_id,omitempty"`
	WorkflowName  *string    `json:"workflow_name,omitempty"`
}

// ListWorkflowsParams defines parameters for ListWorkflows.
type ListWorkflowsParams struct {
	// State Optional filter by workflow state.
	State *WorkflowState `form:"state,omitempty" json:"state,omitempty"`
}

// DownloadWorkflowLogParams defines parameters for DownloadWorkflowLog.
type DownloadWorkflowLogParams struct {
	// View When true, display the log inline as a web page instead of downloading as an attachment.
	View *bool `form:"view,omitempty" json:"view,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetBuildInfo Get orchestrator build and version information
	// (GET /buildinfo)
	GetBuildInfo(w http.ResponseWriter, r *http.Request)
	// GetConfig Current orchestrator configuration (structured summary)
	// (GET /config)
	GetConfig(w http.ResponseWriter, r *http.Request)
	// DownloadConfigFile Download the raw YAML configuration file
	// (GET /config/file)
	DownloadConfigFile(w http.ResponseWriter, r *http.Request)
	// StreamEvents Server-Sent Events stream of pool and workflow state changes
	// (GET /events)
	StreamEvents(w http.ResponseWriter, r *http.Request)
	// ListPools List VM pools and the VMs within each pool
	// (GET /pools)
	ListPools(w http.ResponseWriter, r *http.Request)
	// GetServiceStatus Status of the launchd login service
	// (GET /service)
	GetServiceStatus(w http.ResponseWriter, r *http.Request)
	// RestartService Restart the orchestrator login service
	// (POST /service/restart)
	RestartService(w http.ResponseWriter, r *http.Request)
	// UninstallService Uninstall and stop the orchestrator login service
	// (POST /service/uninstall)
	UninstallService(w http.ResponseWriter, r *http.Request)
	// ListWorkflows List running and recently-completed workflow jobs
	// (GET /workflows)
	ListWorkflows(w http.ResponseWriter, r *http.Request, params ListWorkflowsParams)
	// GetWorkflow Get a single workflow job by its runner-instance name
	// (GET /workflows/{name})
	GetWorkflow(w http.ResponseWriter, r *http.Request, name string)
	// CancelWorkflow Cancel a running workflow job (cancels the GitHub run, which tears down its VM)
	// (POST /workflows/{name}/cancel)
	CancelWorkflow(w http.ResponseWriter, r *http.Request, name string)
	// ListWorkflowLogs List downloadable log artifacts for a workflow job
	// (GET /workflows/{name}/logs)
	ListWorkflowLogs(w http.ResponseWriter, r *http.Request, name string)
	// DownloadWorkflowLog Download a specific log artifact for a workflow job
	// (GET /workflows/{name}/logs/{artifact})
	DownloadWorkflowLog(w http.ResponseWriter, r *http.Request, name string, artifact string, params DownloadWorkflowLogParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetBuildInfo operation middleware
func (siw *ServerInterfaceWrapper) GetBuildInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBuildInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConfig operation middleware
func (siw *ServerInterfaceWrapper) GetConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadConfigFile operation middleware
func (siw *ServerInterfaceWrapper) DownloadConfigFile(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadConfigFile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamEvents operation middleware
func (siw *ServerInterfaceWrapper) StreamEvents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPools operation middleware
func (siw *ServerInterfaceWrapper) ListPools(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPools(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetServiceStatus operation middleware
func (siw *ServerInterfaceWrapper) GetServiceStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetServiceStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestartService operation middleware
func (siw *ServerInterfaceWrapper) RestartService(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestartService(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UninstallService operation middleware
func (siw *ServerInterfaceWrapper) UninstallService(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UninstallService(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkflows operation middleware
func (siw *ServerInterfaceWrapper) ListWorkflows(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWorkflowsParams

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkflows(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkflow operation middleware
func (siw *ServerInterfaceWrapper) GetWorkflow(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkflow(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelWorkflow operation middleware
func (siw *ServerInterfaceWrapper) CancelWorkflow(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelWorkflow(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkflowLogs operation middleware
func (siw *ServerInterfaceWrapper) ListWorkflowLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkflowLogs(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadWorkflowLog operation middleware
func (siw *ServerInterfaceWrapper) DownloadWorkflowLog(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "artifact" -------------
	var artifact string

	err = runtime.BindStyledParameterWithOptions("simple", "artifact", r.PathValue("artifact"), &artifact, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artifact", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DownloadWorkflowLogParams

	// ------------- Optional query parameter "view" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "view", r.URL.Query(), &params.View, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "view"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "view", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadWorkflowLog(w, r, name, artifact, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/config", wrapper.GetConfig)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/buildinfo", wrapper.GetBuildInfo)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/config/file", wrapper.DownloadConfigFile)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/pools", wrapper.ListPools)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/workflows", wrapper.ListWorkflows)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/workflows/{name}", wrapper.GetWorkflow)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/workflows/{name}/cancel", wrapper.CancelWorkflow)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/workflows/{name}/logs", wrapper.ListWorkflowLogs)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/workflows/{name}/logs/{artifact}", wrapper.DownloadWorkflowLog)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/events", wrapper.StreamEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/service", wrapper.GetServiceStatus)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/service/restart", wrapper.RestartService)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/service/uninstall", wrapper.UninstallService)

	return m
}

type GetBuildInfoRequestObject struct {
}

type GetBuildInfoResponseObject interface {
	VisitGetBuildInfoResponse(w http.ResponseWriter) error
}

type GetBuildInfo200JSONResponse BuildInfo

func (response GetBuildInfo200JSONResponse) VisitGetBuildInfoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetConfigRequestObject struct {
}

type GetConfigResponseObject interface {
	VisitGetConfigResponse(w http.ResponseWriter) error
}

type GetConfig200JSONResponse ConfigSummary

func (response GetConfig200JSONResponse) VisitGetConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadConfigFileRequestObject struct {
}

type DownloadConfigFileResponseObject interface {
	VisitDownloadConfigFileResponse(w http.ResponseWriter) error
}

type DownloadConfigFile200ApplicationyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response DownloadConfigFile200ApplicationyamlResponse) VisitDownloadConfigFileResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadConfigFile404JSONResponse Error

func (response DownloadConfigFile404JSONResponse) VisitDownloadConfigFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StreamEventsRequestObject struct {
}

type StreamEventsResponseObject interface {
	VisitStreamEventsResponse(w http.ResponseWriter) error
}

type StreamEvents200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response StreamEvents200TexteventStreamResponse) VisitStreamEventsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type ListPoolsRequestObject struct {
}

type ListPoolsResponseObject interface {
	VisitListPoolsResponse(w http.ResponseWriter) error
}

type ListPools200JSONResponse []PoolStatus

func (response ListPools200JSONResponse) VisitListPoolsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetServiceStatusRequestObject struct {
}

type GetServiceStatusResponseObject interface {
	VisitGetServiceStatusResponse(w http.ResponseWriter) error
}

type GetServiceStatus200JSONResponse ServiceStatus

func (response GetServiceStatus200JSONResponse) VisitGetServiceStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RestartServiceRequestObject struct {
}

type RestartServiceResponseObject interface {
	VisitRestartServiceResponse(w http.ResponseWriter) error
}

type RestartService200Response struct {
}

func (response RestartService200Response) VisitRestartServiceResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type RestartService400JSONResponse Error

func (response RestartService400JSONResponse) VisitRestartServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UninstallServiceRequestObject struct {
}

type UninstallServiceResponseObject interface {
	VisitUninstallServiceResponse(w http.ResponseWriter) error
}

type UninstallService200Response struct {
}

func (response UninstallService200Response) VisitUninstallServiceResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UninstallService400JSONResponse Error

func (response UninstallService400JSONResponse) VisitUninstallServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListWorkflowsRequestObject struct {
	Params ListWorkflowsParams
}

type ListWorkflowsResponseObject interface {
	VisitListWorkflowsResponse(w http.ResponseWriter) error
}

type ListWorkflows200JSONResponse []WorkflowStatus

func (response ListWorkflows200JSONResponse) VisitListWorkflowsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetWorkflowRequestObject struct {
	Name string `json:"name"`
}

type GetWorkflowResponseObject interface {
	VisitGetWorkflowResponse(w http.ResponseWriter) error
}

type GetWorkflow200JSONResponse WorkflowStatus

func (response GetWorkflow200JSONResponse) VisitGetWorkflowResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetWorkflow404JSONResponse Error

func (response GetWorkflow404JSONResponse) VisitGetWorkflowResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelWorkflowRequestObject struct {
	Name string `json:"name"`
}

type CancelWorkflowResponseObject interface {
	VisitCancelWorkflowResponse(w http.ResponseWriter) error
}

type CancelWorkflow202Response struct {
}

func (response CancelWorkflow202Response) VisitCancelWorkflowResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type CancelWorkflow404JSONResponse Error

func (response CancelWorkflow404JSONResponse) VisitCancelWorkflowResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelWorkflow500JSONResponse Error

func (response CancelWorkflow500JSONResponse) VisitCancelWorkflowResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListWorkflowLogsRequestObject struct {
	Name string `json:"name"`
}

type ListWorkflowLogsResponseObject interface {
	VisitListWorkflowLogsResponse(w http.ResponseWriter) error
}

type ListWorkflowLogs200JSONResponse []LogArtifact

func (response ListWorkflowLogs200JSONResponse) VisitListWorkflowLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListWorkflowLogs404JSONResponse Error

func (response ListWorkflowLogs404JSONResponse) VisitListWorkflowLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadWorkflowLogRequestObject struct {
	Name     string `json:"name"`
	Artifact string `json:"artifact"`
	Params   DownloadWorkflowLogParams
}

type DownloadWorkflowLogResponseObject interface {
	VisitDownloadWorkflowLogResponse(w http.ResponseWriter) error
}

type DownloadWorkflowLog200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response DownloadWorkflowLog200ApplicationoctetStreamResponse) VisitDownloadWorkflowLogResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadWorkflowLog404JSONResponse Error

func (response DownloadWorkflowLog404JSONResponse) VisitDownloadWorkflowLogResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetBuildInfo Get orchestrator build and version information
	// (GET /buildinfo)
	GetBuildInfo(ctx context.Context, request GetBuildInfoRequestObject) (GetBuildInfoResponseObject, error)
	// GetConfig Current orchestrator configuration (structured summary)
	// (GET /config)
	GetConfig(ctx context.Context, request GetConfigRequestObject) (GetConfigResponseObject, error)
	// DownloadConfigFile Download the raw YAML configuration file
	// (GET /config/file)
	DownloadConfigFile(ctx context.Context, request DownloadConfigFileRequestObject) (DownloadConfigFileResponseObject, error)
	// StreamEvents Server-Sent Events stream of pool and workflow state changes
	// (GET /events)
	StreamEvents(ctx context.Context, request StreamEventsRequestObject) (StreamEventsResponseObject, error)
	// ListPools List VM pools and the VMs within each pool
	// (GET /pools)
	ListPools(ctx context.Context, request ListPoolsRequestObject) (ListPoolsResponseObject, error)
	// GetServiceStatus Status of the launchd login service
	// (GET /service)
	GetServiceStatus(ctx context.Context, request GetServiceStatusRequestObject) (GetServiceStatusResponseObject, error)
	// RestartService Restart the orchestrator login service
	// (POST /service/restart)
	RestartService(ctx context.Context, request RestartServiceRequestObject) (RestartServiceResponseObject, error)
	// UninstallService Uninstall and stop the orchestrator login service
	// (POST /service/uninstall)
	UninstallService(ctx context.Context, request UninstallServiceRequestObject) (UninstallServiceResponseObject, error)
	// ListWorkflows List running and recently-completed workflow jobs
	// (GET /workflows)
	ListWorkflows(ctx context.Context, request ListWorkflowsRequestObject) (ListWorkflowsResponseObject, error)
	// GetWorkflow Get a single workflow job by its runner-instance name
	// (GET /workflows/{name})
	GetWorkflow(ctx context.Context, request GetWorkflowRequestObject) (GetWorkflowResponseObject, error)
	// CancelWorkflow Cancel a running workflow job (cancels the GitHub run, which tears down its VM)
	// (POST /workflows/{name}/cancel)
	CancelWorkflow(ctx context.Context, request CancelWorkflowRequestObject) (CancelWorkflowResponseObject, error)
	// ListWorkflowLogs List downloadable log artifacts for a workflow job
	// (GET /workflows/{name}/logs)
	ListWorkflowLogs(ctx context.Context, request ListWorkflowLogsRequestObject) (ListWorkflowLogsResponseObject, error)
	// DownloadWorkflowLog Download a specific log artifact for a workflow job
	// (GET /workflows/{name}/logs/{artifact})
	DownloadWorkflowLog(ctx context.Context, request DownloadWorkflowLogRequestObject) (DownloadWorkflowLogResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetBuildInfo operation middleware
func (sh *strictHandler) GetBuildInfo(w http.ResponseWriter, r *http.Request) {
	var request GetBuildInfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBuildInfo(ctx, request.(GetBuildInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBuildInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBuildInfoResponseObject); ok {
		if err := validResponse.VisitGetBuildInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetConfig operation middleware
func (sh *strictHandler) GetConfig(w http.ResponseWriter, r *http.Request) {
	var request GetConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetConfig(ctx, request.(GetConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetConfigResponseObject); ok {
		if err := validResponse.VisitGetConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadConfigFile operation middleware
func (sh *strictHandler) DownloadConfigFile(w http.ResponseWriter, r *http.Request) {
	var request DownloadConfigFileRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadConfigFile(ctx, request.(DownloadConfigFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadConfigFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadConfigFileResponseObject); ok {
		if err := validResponse.VisitDownloadConfigFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StreamEvents operation middleware
func (sh *strictHandler) StreamEvents(w http.ResponseWriter, r *http.Request) {
	var request StreamEventsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StreamEvents(ctx, request.(StreamEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StreamEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StreamEventsResponseObject); ok {
		if err := validResponse.VisitStreamEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPools operation middleware
func (sh *strictHandler) ListPools(w http.ResponseWriter, r *http.Request) {
	var request ListPoolsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPools(ctx, request.(ListPoolsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPools")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPoolsResponseObject); ok {
		if err := validResponse.VisitListPoolsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetServiceStatus operation middleware
func (sh *strictHandler) GetServiceStatus(w http.ResponseWriter, r *http.Request) {
	var request GetServiceStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetServiceStatus(ctx, request.(GetServiceStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetServiceStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetServiceStatusResponseObject); ok {
		if err := validResponse.VisitGetServiceStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RestartService operation middleware
func (sh *strictHandler) RestartService(w http.ResponseWriter, r *http.Request) {
	var request RestartServiceRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RestartService(ctx, request.(RestartServiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RestartService")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RestartServiceResponseObject); ok {
		if err := validResponse.VisitRestartServiceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UninstallService operation middleware
func (sh *strictHandler) UninstallService(w http.ResponseWriter, r *http.Request) {
	var request UninstallServiceRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UninstallService(ctx, request.(UninstallServiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UninstallService")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UninstallServiceResponseObject); ok {
		if err := validResponse.VisitUninstallServiceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListWorkflows operation middleware
func (sh *strictHandler) ListWorkflows(w http.ResponseWriter, r *http.Request, params ListWorkflowsParams) {
	var request ListWorkflowsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListWorkflows(ctx, request.(ListWorkflowsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListWorkflows")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListWorkflowsResponseObject); ok {
		if err := validResponse.VisitListWorkflowsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWorkflow operation middleware
func (sh *strictHandler) GetWorkflow(w http.ResponseWriter, r *http.Request, name string) {
	var request GetWorkflowRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkflow(ctx, request.(GetWorkflowRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkflow")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWorkflowResponseObject); ok {
		if err := validResponse.VisitGetWorkflowResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelWorkflow operation middleware
func (sh *strictHandler) CancelWorkflow(w http.ResponseWriter, r *http.Request, name string) {
	var request CancelWorkflowRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelWorkflow(ctx, request.(CancelWorkflowRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelWorkflow")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelWorkflowResponseObject); ok {
		if err := validResponse.VisitCancelWorkflowResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListWorkflowLogs operation middleware
func (sh *strictHandler) ListWorkflowLogs(w http.ResponseWriter, r *http.Request, name string) {
	var request ListWorkflowLogsRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListWorkflowLogs(ctx, request.(ListWorkflowLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListWorkflowLogs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListWorkflowLogsResponseObject); ok {
		if err := validResponse.VisitListWorkflowLogsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadWorkflowLog operation middleware
func (sh *strictHandler) DownloadWorkflowLog(w http.ResponseWriter, r *http.Request, name string, artifact string, params DownloadWorkflowLogParams) {
	var request DownloadWorkflowLogRequestObject

	request.Name = name
	request.Artifact = artifact
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadWorkflowLog(ctx, request.(DownloadWorkflowLogRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadWorkflowLog")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadWorkflowLogResponseObject); ok {
		if err := validResponse.VisitDownloadWorkflowLogResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFptc9u48f8qGP7/M01mZEm2c9fWfeXmcld37LuMlXOmPXtkiFyRsEGAAUApuoy/e2cBkOIDKEu5Js0r",
	"0+Risdj97SP0KYplXkgBwujo7FOk4wxyah//XjKeXIilxH8KJQtQhoH9RFWc4V/4SPOCQ3QWUZV//yoa",
	"RWZT4L/aKCbS6GkULZDL3LAc2gtOpiffH03/ejQ9fXf8l7Pp9Gw6/XdofSrnK1CaSdFen8rj8cmr8TS0",
	"JpcJWzJIWiuWlGuoiRdScqACqaVuc06oWjMR4ltQ0zl2ykxWLsaxzCcxl2UCImVyEjMjJdcTVQoBSk9y",
	"Gks9kSrOQBtFjVQh7gpWrH9OmE6/g1M6XRzHJ+PxeNfCuc6kMuHlO9ftts6fz46/G7JO0DSr6fg4ZBi7",
	"5YeSKbTMb03LWiOMHKzu6nVy8QCxwW1eS7Fk6azMc6o2fTjG9vN8ybg9RgI6VqwwVrDoLTUZMZKYDMi/",
	"zq8uiaMmSE1MxjRpGoasqSbaUGUgIWtmsqDGUy4XlONe/69gGZ1F/zfZutHE+9DkJ0vVlh1RhNjAtcxA",
	"rp9j8lbKPgsvEFWKbpwlC6mZkYrB/pyvq0WbHZzXsMikfHyO13tHVjPqmLppoFp7HbErxWz3DCHhjVJS",
	"9REA1evdkHNkQb4rEKbPF0Xax0IzQ02prQJZDtrQvMBlS6lyamxMMXCEn0Joci8+RSDKHKW0m46itVSP",
	"Sy7X0SjKgHMZ3QXW1kTPGcjTVYJ2FGP5NoUP6SiE54AvYhRA35t/KKGEuWa/Q8MyTBhIQSG/JWUckvkq",
	"nyswIOyaAhSTSd+Lf5IkKRXF/4g7/YjAOB2T2+h0mt9GQTfVZRyD1suSD23St0VezBM2AKWeRi5leq4M",
	"W9LYBKMSbjivzNvbC91B0Dz8MbPG7KrhGjg1bAXk1+tLDGqJXAsuaeICGfWyBJXBAlqdGbrgUK8jLKm1",
	"+iAXtxGRitxGCaPpkIbZ7zBfbAzoFtyZMM1qoLZ5B3UsiRpa8GcOIa8fBHvaZjlNw5ocVLFLzwPmdmcL",
	"AfdpQEDvWgdI9shEwCjvMiA3V2RB40cQCUEispTKmRhjQ20jTFMDhhk8dHWq9p5OuaWCxO5AkIq8MFSl",
	"YIgo8wUoIpdkTVVObq70y3HAuKNole+ffW6uGjGzlXQ6IPHYsHK7LUII6Seznh3kWkDY0piHdiDkgJRq",
	"6QfTaQg57SU9oTldQKdaGMgf25yNGpsXCpbsY5B+lc+rvLZHjJuBWrEYBtEttKGcQwDI7zMwGShbeXFa",
	"ijhLCJcpE0Q7noRpUq8fR6Hi3J4/7CMVE0tCJmRRioQDufghXCSXQuDjTilblSDTJC6VAmH4hvjlhGpC",
	"q51DEncjXK2drQQh+DpvgGCENoCuRzEmUE0Qq7Y4XWysyGhJFKQqHmIF1OA2o0gbmronuqKMY6jH59iL",
	"hwSyKOxTAhyMfXJJORpFpXgUci2CVcfN1RAc7PaQzKnZv/5h4VTMqTZzqOqyvv1zqQ1REIMwLmhZWhcv",
	"5QJtBI3AeXN1WJwc8BCrVQPPBYLKnk+jqCySAzUSypJu1xB0OqV3zyIKON3MS7WvvzcrxQAgL9kS4k3M",
	"gegtNKsqlDzIhe2amOj505jcr/K5Lw8huSc5UKEtGa5aMsF0BgmRbimXMeU2D5aG/MTMP8oFyagmQhqy",
	"AUMS4GwFmLCQelt1Et89/I3c9/bybGiMyOaQpJA0Vo5vRcOPbPGa1P7i/KhyYRtDa/bRKGo+1x4UUxED",
	"PoZcqFOQD9XRNXB6QUs8d5xotBfaRtvmqb2HbbVIAoYyTthyayl7PuJ75eqQQe96kIu58+5nS0NHPOiO",
	"+NFjuC2lL4RRuBqFqhRWUlnr6IWtmDJjCn02mTSmNrfldHoa29LAPoJ/g2HWv6AxbmWnObr6Woo5S/z3",
	"B7nwr91x3euXQYV8TjrnMt2/Aml2JAOlQTiaulLHpWMRA0FKQrVmqdgmm5Y/R6MDoqZzp4PSAppgviw5",
	"H0aFJQmHNvyoSx7KHaByJignjgChXTtbXVrPsHWEBJKB+tohYE9k+3nSQaffK820Y/VTOywNB45ezK2q",
	"m07s3T+ErPL5QBavnHLIiAPV/kC6Q3LmR9LdzpgmR1LwDcmpoCnkIAw5f3tB4GMhdRjCf9LkXpXiHu2f",
	"U5GMyYXxBZZLTL7+8yNDP38Y2U919jOuXbPDK0JF4l/oRh7MR/UHH4+aCbNZZr6Qypc0fPOyMsuIMBHz",
	"MkELVQ2/7du5dGNM7VKXYcbOX/0errMgvzRr2vO3F1Fjahu5Se3TKJIFCFqw6Cw6HU/Hp5EbdttwM7Ej",
	"/ErrKVhUYaqy2rhIcEcw29sC63mFFNolspPptDENwUdaFJzFdvXkQbvpsUP0c3jfbmKR0EaA/WgV7c/n",
	"c5f2RSBsYd5UyYIJqjZji0RdFVF4og5ZjzsTzjfcANtQjNK/RXqjDeTRHbKbONzsUptrvL+kzjrD477e",
	"3g0BvauT156opZfWCvJCG1XGxg4S/MKXDeU44pZyJtXUPqihHzzc3SF+dPPjA1S1oTlvq6qOZ87ugeo7",
	"qCBF152jotzYkKF42GgomZOE6ccxutOr6av/mgHdyHvIcH2Z0HGxefUNHBZqpVDgYkbXpj9sB4jukI0r",
	"kibXISPanks37NcW8ZwY+Ggc1ZE2CmiOMdMGz6M4oyIF17bpMXlD48z9g3E5oYbekyUDnuBhKPnn7Jef",
	"j0DEErVtx/XEZYUxec0ZsiA6kyVPMIBKEbvrHWDKp7MVgzUmOKi3sd6c0w1ZUs7tvK2qJK/fzN4REEkh",
	"mTAuflCCpQjRghY6k8ZF3DZYZ/Z8b5xGnoVpTzEHIAJXhRBxLshs9oY4fl1T4yAH1NEMT+6EJFuL2AYa",
	"9VFnJpfgnI10w/ze4s789V1W0HsvmTZv/aXOH4pve9+UDc4Ud0a9OpfDCtSmRj8kVWLvqhIPtjPpW5D5",
	"e5xKcZbY681PkHZlhvbc7QsmiPZGAVV5AqumUvdgZd9WlVBwztdMj/5NSw0TBbZEdjduOqCPa0cwq/mF",
	"tBGW2vMmTDDDcBLjA/T0ywfo2XbMKaTZjjqJVLVYrpvuKtWftz+UPEyvpfB7Dmv214rkc3Rb87fpvrps",
	"45tvQ8W1dANKro9uPVgbWXyuvquguTsUvq+psLpWNAdjLxd+66r3F/tAOWZeAwpbl3ZYxsaMIeWHEmwN",
	"45or3zaN9lRqp3t8uvsaUbp7Ef18pL6uRu8iqXujo7rLbbdSwUCtDmDQMPHWqB0jTz6hup92Be/327v7",
	"jqWt2ewPiWqr2T/NNtioEppG7Faod18wG/R+KBDMnE2dfb2C92eJUSardw81bZRoJlLeFhE9iBnth1xH",
	"rSHXARafuGHncDB9bb9/beOfBO5zrSDc1e9re230oQS9zX5f0VqV+zWsNoq++xrJ4Uc3qTayOj6JG3rp",
	"tbf2G6E9gS2CXrilujnFUaUYkXXG4owYoErb6YwF2s3Vy0NwVY14n00dl0j4TcaUPz6dDkea+urSTruq",
	"X6robyfo2BTTG8vVgvrmsYmlQ5Ex+VRxe3p2UNIAypfBySh0ebD3D4gCElRr/5gUbq6Nq3AIU3C68ZPs",
	"lDDBmQB3c7+GBSloCrZQBJpg21LZrrreF4QaQ+MsB2GGCi0cJkQBAbe/AzjMn2RsIDwH+Mx5VRODxG/6",
	"v/MZhMH2x2kDEyhKdAExW7K4Lf3+DoR87ZDDwd1eDEUTWrDJ6jh6unv6zwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
