/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current orchestrator configuration (structured summary) */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the raw YAML configuration file */
        get: operations["downloadConfigFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List VM pools and the VMs within each pool */
        get: operations["listPools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List running and recently-completed workflow jobs */
        get: operations["listWorkflows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single workflow job by its runner-instance name */
        get: operations["getWorkflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{name}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List downloadable log artifacts for a workflow job */
        get: operations["listWorkflowLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{name}/logs/{artifact}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a specific log artifact for a workflow job */
        get: operations["downloadWorkflowLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream of pool and workflow state changes
         * @description A text/event-stream of state-change events. Each event's `data` field is a JSON-encoded Event object. Clients should reconcile their local view on each event and may fall back to the REST endpoints for a full snapshot.
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        /**
         * @description Lifecycle state of a workflow job within the orchestrator. `vm_completed` means the job finished on the local VM but GitHub has not yet delivered the completion webhook; `completed` means GitHub acknowledged completion.
         * @enum {string}
         */
        WorkflowState: "queued" | "acquiring" | "running" | "vm_completed" | "completed" | "failed" | "canceled";
        /**
         * @description State of a VM as reported by the pool.
         * @enum {string}
         */
        VMState: "creating" | "staging" | "available" | "acquired" | "stopped" | "deleted" | "failed" | "unknown";
        ConfigSummary: {
            /** @description Path to the YAML config file this orchestrator was started with. */
            config_file: string;
            global: components["schemas"]["GlobalConfigSummary"];
            repositories: components["schemas"]["RepositorySummary"][];
            pools: components["schemas"]["PoolConfigSummary"][];
            webhook: components["schemas"]["WebhookSummary"];
        };
        GlobalConfigSummary: {
            tmp_dir?: string;
            completion_queue_size?: number;
            /** @description Go duration string, e.g. "30m". */
            failed_vm_retention_period?: string;
            successful_vm_retention_period?: string;
        };
        RepositorySummary: {
            owner?: string;
            repo?: string;
            runners?: components["schemas"]["RunnerSummary"][];
        };
        RunnerSummary: {
            name_prefix?: string;
            labels?: string[];
            vm_pool?: string;
        };
        PoolConfigSummary: {
            name?: string;
            image?: string;
            size?: number;
            runner_dir?: string;
        };
        WebhookSummary: {
            relay_url?: string;
        };
        PoolStatus: {
            name: string;
            image?: string;
            /** @description Configured pool size (target number of warm VMs). */
            size: number;
            vms: components["schemas"]["VMStatus"][];
        };
        VMStatus: {
            id: string;
            name?: string;
            pool?: string;
            state: components["schemas"]["VMState"];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** @description The most recent pool event kind observed for this VM. */
            last_event?: string;
        };
        WorkflowStatus: {
            /** @description The runner instance name assigned by the orchestrator. */
            name: string;
            state: components["schemas"]["WorkflowState"];
            repo_full_name?: string;
            repo_url?: string;
            workflow_name?: string;
            job_name?: string;
            /** Format: int64 */
            job_id?: number;
            labels?: string[];
            pool?: string;
            vm_id?: string;
            /** @description Terminal result if completed, e.g. "Succeeded". */
            result?: string;
            /** @description Error detail if the job failed or was canceled. */
            error?: string;
            /** Format: date-time */
            queued_at?: string;
            /** Format: date-time */
            started_at?: string;
            /**
             * Format: date-time
             * @description When the job finished running on the local VM.
             */
            vm_completed_at?: string;
            /**
             * Format: date-time
             * @description When GitHub acknowledged completion.
             */
            completed_at?: string;
            logs?: components["schemas"]["LogArtifact"][];
        };
        LogArtifact: {
            /** @description Stable artifact id, e.g. "job" or "diag". */
            id: string;
            filename: string;
            content_type?: string;
            /** Format: int64 */
            size_bytes?: number;
            /** @description Relative URL to download this artifact. */
            href: string;
        };
        Event: {
            /** @enum {string} */
            type: "pool" | "workflow" | "hello";
            /** Format: date-time */
            timestamp: string;
            pool?: components["schemas"]["PoolStatus"];
            workflow?: components["schemas"]["WorkflowStatus"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSummary"];
                };
            };
        };
    };
    downloadConfigFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The raw configuration file as loaded from disk. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
            /** @description The configuration file path is unknown or unreadable. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listPools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current state of every configured VM pool. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolStatus"][];
                };
            };
        };
    };
    listWorkflows: {
        parameters: {
            query?: {
                /** @description Optional filter by workflow state. */
                state?: components["schemas"]["WorkflowState"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Running and recently-completed workflow jobs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStatus"][];
                };
            };
        };
    };
    getWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workflow job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStatus"];
                };
            };
            /** @description No such workflow. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listWorkflowLogs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The available log artifacts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogArtifact"][];
                };
            };
            /** @description No such workflow. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    downloadWorkflowLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                /** @description The artifact id, e.g. "job" or "diag". */
                artifact: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The log artifact content. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description No such workflow or artifact. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An SSE stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["Event"];
                };
            };
        };
    };
}
