# macOS Tart Orchestrator Configuration

logging:
  level: 2
  format: text
  file: "-"

jwt_cookie_spec: &jwt_cookie_spec
  name: "github-runner-orchestrator"
  domain: "127.0.0.1"
  path: "/"
  duration: 240h
  insecure: true

jwt_spec: &jwt_spec
  jwt_issuer: "github-orchestrator"
  jwt_audience: ["github-orchestrator"]
  jwt_subject: "github-orchestrator"
  jwt_claims:
    access: admin

web_ui:
  enabled: true
  listen_address: 127.0.0.1:9088
  jwt_verifier:
    cookie:
      <<: *jwt_cookie_spec
    <<: *jwt_spec
    validation_time_skew: 1m
    jwt_verification_keys:
      - user: cnicolaou
        key_id: "github-orchestrator-jwt-key"

jwt_issuer:
  cookie:
    <<: *jwt_cookie_spec
  <<: *jwt_spec
  jwt_signing_key:
    key_id: github-orchestrator-jwt-key
    user: cnicolaou

global:
  tmp_dir: "github-orchestrator-*"
  search_paths:
    - /opt/homebrew/bin
    - /usr/local/bin
  completion_queue_size: 1000
  failed_vm_retention_period: 1h
  successful_vm_retention_period: 15m

vm_pools:
  macos:
    size: 2
    delete_acquired_on_close: true
    tart_config:
      os: macos
      runner_dir: /Users/admin/actions-runner
      image: macos-ci
      binary: /opt/homebrew/bin/tart

  linux:
    size: 2
    delete_acquired_on_close: true
    tart_config:
      os: linux
      runner_dir: "/home/admin/actions-runner"
      image: linux-ci
      run_options: ["--no-graphics", "--no-audio", "--nested"]
      binary: /opt/homebrew/bin/tart

icloud_keychain:
  keychain_type: all
  items:
    - cloudengio-github-runner
    - onyourbehalf-github-runner
    - webhook-secrets
    - cloudengio-jwt-signing-keys

runners: &runner_config
  - name_prefix: "go-macos"
    vm_pool: "macos"
    labels: ["self-hosted", "macos", "arm64"]
    replace: true
    ephemeral: true
    timeout: 30m

  - name_prefix: "go-linux"
    vm_pool: "linux"
    labels: ["self-hosted", "linux", "arm64"]
    replace: true
    ephemeral: true
    timeout: 30m

cloudeng_repos: &cloudeng_repos
  owner: "cloudengio"
  key_id: github-cloudengio-runner-token
  user_id: cnicolaou
  runners: *runner_config

onyourbehalf_token: &onyourbehalf_token
  key_id: github-onyourbehalf-runner-token
  user_id: cnicolaou

repositories:
  - repo: "go.pkgs"
    <<: *cloudeng_repos
  - repo: "go.webapp"
    <<: *cloudeng_repos
  - repo: "go.webapi"
    <<: *cloudeng_repos
  - repo: "go.macos"
    <<: *cloudeng_repos
  - repo: "citools"
    <<: *cloudeng_repos
  - owner: "onyourbehalf"
    repo: "core"
    <<: *onyourbehalf_token
    runners: *runner_config

webhook:
  relay_url: "https://onyourbehalf.ai:10444/webhooks/github_workflows/relay"
  rate_control:
    exponential_backoff:
      initial_delay: 1s
      steps: 10
