// Copyright 2026 cloudeng llc. All rights reserved.
// Use of this source code is governed by the Apache-2.0
// license that can be found in the LICENSE file.

package vmsclient

import (
	"slices"
	"testing"

	"cloudeng.io/macos/tartvm"
)

func poolConfigs() map[string]PoolConfig {
	macos := PoolConfig{}
	macos.TartConfig.Image = "macos-ci"
	linux := PoolConfig{}
	linux.TartConfig.Image = "linux-ci"
	return map[string]PoolConfig{"macos": macos, "linux": linux}
}

func TestFilterTartVMs(t *testing.T) {
	cfgs := poolConfigs()
	all := tartvm.ListEntries{
		// Created by the orchestrator, one per configured pool.
		{Source: "local", Name: VMSPrefix + "macos-macos-ci-20260804-152144"},
		{Source: "local", Name: VMSPrefix + "linux-linux-ci-20260804-151500"},
		// The base images the pools clone from.
		{Source: "local", Name: "macos-ci"},
		{Source: "local", Name: "linux-ci"},
		// Pre-existing VMs using the older, unprefixed naming convention.
		{Source: "local", Name: "macos-macos-ci-20260804-152144"},
		// A pool that is not configured.
		{Source: "local", Name: VMSPrefix + "windows-windows-ci-20260804-152144"},
		// The pool name matches but the image does not.
		{Source: "local", Name: VMSPrefix + "macos-linux-ci-20260804-152144"},
		// OCI images are never candidates for deletion.
		{Source: "OCI", Name: VMSPrefix + "macos-macos-ci-20260804-152145"},
	}
	want := []string{
		VMSPrefix + "macos-macos-ci-20260804-152144",
		VMSPrefix + "linux-linux-ci-20260804-151500",
	}
	got := []string{}
	for _, entry := range filterTartVMs(all, cfgs) {
		got = append(got, entry.Name)
	}
	if !slices.Equal(got, want) {
		t.Errorf("got %v, want %v", got, want)
	}
}

func TestFilterTartVMsNoTartPools(t *testing.T) {
	all := tartvm.ListEntries{
		{Source: "local", Name: VMSPrefix + "macos-macos-ci-20260804-152144"},
	}
	if got := filterTartVMs(all, map[string]PoolConfig{"macos": {}}); len(got) != 0 {
		t.Errorf("got %v, want no entries", got)
	}
}

func TestVMNamePrefix(t *testing.T) {
	// The prefix must match the names generated by TartConstructor.New.
	c := NewTartConstructor(t.Context(), "macos", "macos-ci")
	name := c.New().ID()
	if got, want := name[:len(vmNamePrefix("macos", "macos-ci"))], vmNamePrefix("macos", "macos-ci"); got != want {
		t.Errorf("%v: got %v, want %v", name, got, want)
	}
}
