// Copyright 2026 cloudeng llc. All rights reserved.
// Use of this source code is governed by the Apache-2.0
// license that can be found in the LICENSE file.

package vmsclient

import (
	"context"
	"errors"
	"log/slog"
	"testing"
)

func tartPool(image string) PoolConfig {
	return PoolConfig{Tart: &TartConfig{Image: image}}
}

func TestVMNamePrefix(t *testing.T) {
	// The prefix must match the names generated by tartProvider.New.
	p := newTartProvider("macos", TartConfig{Image: "macos-ci"}, slog.Default())
	inst, err := p.New(context.Background())
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	name := inst.ID()
	if got, want := name[:len(vmNamePrefix("macos", "macos-ci"))], vmNamePrefix("macos", "macos-ci"); got != want {
		t.Errorf("%v: got %v, want %v", name, got, want)
	}
}

func TestProviderSelection(t *testing.T) {
	// A tart-configured pool yields a tart provider.
	p, err := tartPool("macos-ci").newProvider("macos", slog.Default())
	if err != nil {
		t.Fatal(err)
	}
	if p.Kind() != "tart" || p.Image() != "macos-ci" {
		t.Errorf("unexpected provider: kind=%q image=%q", p.Kind(), p.Image())
	}
	// A pool with no backend configured is rejected.
	if _, err := (PoolConfig{}).newProvider("empty", slog.Default()); !errors.Is(err, ErrNoBackend) {
		t.Errorf("empty pool: got %v, want ErrNoBackend", err)
	}
}
