// Copyright 2026 cloudeng llc. All rights reserved.
// Use of this source code is governed by the Apache-2.0
// license that can be found in the LICENSE file.

package vmsclient

import (
	"context"
	"fmt"
	"io"
	"log/slog"
	"os/exec"
	"slices"
	"strconv"
	"strings"
	"sync/atomic"
	"time"

	"cloudeng.io/errors"
	"cloudeng.io/logging/ctxlog"
	"cloudeng.io/macos/tartvm"
	"cloudeng.io/sync/errgroup"
	"cloudeng.io/vms"
	"cloudeng.io/vms/vmspool"
)

type TartConstructor struct {
	name   string
	image  string
	logger *slog.Logger
	opts   []tartvm.Option
}

const VMSPrefix = "ghr-orchestrator-"

var vmInstID atomic.Int64

func (c *TartConstructor) New() vms.Instance {
	name := fmt.Sprintf("%s%s-%s-%s-%04d", VMSPrefix, c.name, c.image, time.Now().Format("20060102-150405"), vmInstID.Add(1))
	opts := slices.Clone(c.opts)
	opts = append(opts,
		tartvm.WithLogger(c.logger),
		tartvm.WithObtainIPAtStart(false),
	)
	vm := tartvm.New(context.Background(), c.image, name, opts...)
	return vm
}

func NewTartConstructor(ctx context.Context, name, image string, opts ...tartvm.Option) *TartConstructor {
	return &TartConstructor{
		name:   name,
		image:  image,
		opts:   opts,
		logger: ctxlog.Logger(ctx),
	}
}

// tartLocalSource is the value that "tart list" reports for locally created
// VMs, as opposed to OCI images that have been pulled.
const tartLocalSource = "local"

// vmNamePrefix returns the prefix shared by all of the VM names generated by
// TartConstructor.New for the named pool and image.
func vmNamePrefix(pool, image string) string {
	return fmt.Sprintf("%s%s-%s-", VMSPrefix, pool, image)
}

// ListTartVMs runs "tart list" and returns the entries for all of the local VMs
// whose names match the naming convention used by TartConstructor.New for one
// of the supplied pool configurations. OCI images, and local VMs belonging to
// pools that are not configured, are never returned.
func ListTartVMs(ctx context.Context, poolCfgs map[string]PoolConfig) (tartvm.ListEntries, error) {
	all, err := tartvm.ListAll(ctx)
	if err != nil {
		return nil, err
	}
	return filterTartVMs(all, poolCfgs), nil
}

// filterTartVMs implements the filtering performed by ListTartVMs.
func filterTartVMs(all tartvm.ListEntries, poolCfgs map[string]PoolConfig) tartvm.ListEntries {
	prefixes := make([]string, 0, len(poolCfgs))
	for pool, poolCfg := range poolCfgs {
		if poolCfg.TartConfig.Image != "" {
			prefixes = append(prefixes, vmNamePrefix(pool, poolCfg.TartConfig.Image))
		}
	}
	var matched tartvm.ListEntries
	for _, entry := range all {
		if entry.Source != tartLocalSource {
			continue
		}
		for _, prefix := range prefixes {
			if strings.HasPrefix(entry.Name, prefix) {
				matched = append(matched, entry)
				break
			}
		}
	}
	return matched
}

// DeleteTartVMs runs "tart delete" for every VM returned by ListTartVMs.
// Running VMs are stopped first via "tart stop", waiting up to stopTimeout for
// a graceful shutdown before tart forcibly stops them; a non-positive
// stopTimeout leaves the choice of timeout to tart. Deletion continues past
// errors so that a single failure does not leave the remaining VMs behind. The
// names of the VMs that were deleted are returned along with any accumulated
// errors.
func DeleteTartVMs(ctx context.Context, poolCfgs map[string]PoolConfig, stopTimeout time.Duration) ([]string, error) {
	entries, err := ListTartVMs(ctx, poolCfgs)
	if err != nil {
		return nil, err
	}
	var errs errors.M
	deleted := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.Running {
			args := []string{"stop", entry.Name}
			if stopTimeout > 0 {
				args = append(args, "--timeout", strconv.Itoa(int(stopTimeout.Seconds())))
			}
			if err := runTart(ctx, args...); err != nil {
				// Report the failure but still attempt the delete below, the
				// VM may have exited in the meantime.
				ctxlog.Error(ctx, "failed to stop vm", "vm", entry.Name, "error", err)
				errs.Append(err)
			}
		}
		if err := runTart(ctx, "delete", entry.Name); err != nil {
			ctxlog.Error(ctx, "failed to delete vm", "vm", entry.Name, "error", err)
			errs.Append(err)
			continue
		}
		ctxlog.Info(ctx, "deleted vm", "vm", entry.Name, "state", entry.State)
		deleted = append(deleted, entry.Name)
	}
	return deleted, errs.Err()
}

func runTart(ctx context.Context, args ...string) error {
	out, err := exec.CommandContext(ctx, "tart", args...).CombinedOutput() //nolint:gosec // G204 false positive
	if err != nil {
		return fmt.Errorf("tart %v: %s: %w", strings.Join(args, " "), out, err)
	}
	return nil
}

type TartConfig struct {
	tartvm.Config `yaml:",inline"`
	Image         string `yaml:"image" doc:"base image to use for cloning VMs in this pool"`
	RunnerDir     string `yaml:"runner_dir" doc:"directory on the VM in which the runner was installed, specific to each type of image."`
}

type PoolConfig struct {
	vmspool.Config `yaml:",inline"`
	TartConfig     TartConfig `yaml:"tart_config" doc:"configuration for tart VM pools"`
}

func (cfg PoolConfig) RunnerDir() string {
	if cfg.TartConfig.Image != "" {
		return cfg.TartConfig.RunnerDir
	}
	return ""
}

func (cfg PoolConfig) Validate() error {
	numTypes := 0
	if cfg.TartConfig.Image != "" {
		numTypes++
	}
	if numTypes == 0 {
		return fmt.Errorf("exactly one of tart_config, or other VM pool types must be specified")
	}
	return nil
}

type Pool struct {
	*vmspool.Pool
	name string
}

func (p *Pool) Name() string {
	return p.name
}

type Pools struct {
	pools   map[string]*Pool
	configs map[string]PoolConfig
	tracker *PoolStatusTracker
}

func NewPools(ctx context.Context, cfg map[string]PoolConfig, createFile func(string) io.Writer) (*Pools, error) {
	p := &Pools{
		pools:   make(map[string]*Pool),
		configs: cfg,
		tracker: newPoolStatusTracker(),
	}
	var g errgroup.T
	for name, poolCfg := range cfg {
		var constructor vmspool.Constructor
		if poolCfg.TartConfig.Image != "" {
			constructor = NewTartConstructor(ctx, name, poolCfg.TartConfig.Image, poolCfg.TartConfig.Options()...)
		}
		if constructor == nil {
			return nil, fmt.Errorf("vm_pool %s: no constructor could be created for the specified configuration", name)
		}
		eventCh := make(chan vmspool.Event, 100)
		go func() {
			for e := range eventCh {
				p.tracker.record(name, e)
				ctxlog.Info(ctx, "vm pool event", "pool", name, "event", e.Kind)
			}
		}()
		opts := slices.Clone(poolCfg.Options())
		opts = append(opts,
			vmspool.WithStatus(eventCh),
			vmspool.WithStdoutStderr(createFile, createFile))
		p.pools[name] = &Pool{
			Pool: vmspool.New(constructor, opts...),
			name: name,
		}
		g.Go(func() error {
			ctxlog.Info(ctx, "starting vm pool", "pool", name)
			err := p.pools[name].Start(ctx)
			if err != nil {
				ctxlog.Error(ctx, "failed to start vm pool", "pool", name, "error", err)
			} else {
				ctxlog.Info(ctx, "vm pool started", "pool", name)
			}
			return err
		})
	}
	return p, g.Wait()
}

func (p *Pools) Acquire(ctx context.Context, name string) (*vmspool.VM, error) {
	vmp, ok := p.pools[name]
	if !ok {
		return nil, fmt.Errorf("vm_pool %s: no such pool", name)
	}
	return vmp.Acquire(ctx)
}

func (p *Pools) ClosePool(ctx context.Context, name string) error {
	vmp, ok := p.pools[name]
	if !ok {
		return fmt.Errorf("vm_pool %s: no such pool", name)
	}
	ctxlog.Info(ctx, "closing vm pool", "pool", name)
	return vmp.Close(ctx)
}

func (p *Pools) Close(ctx context.Context) error {
	var g errgroup.T
	for _, vmp := range p.pools {
		g.Go(func() error {
			return vmp.Close(ctx)
		})
	}
	return g.Wait()
}
